# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'outputWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(696, 426)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.List = QtGui.QVBoxLayout()
        self.List.setObjectName(_fromUtf8("List"))
        self.listItem_3 = QtGui.QWidget(self.centralwidget)
        self.listItem_3.setMinimumSize(QtCore.QSize(0, 0))
        self.listItem_3.setMaximumSize(QtCore.QSize(10000, 100))
        self.listItem_3.setObjectName(_fromUtf8("listItem_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.listItem_3)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.nameLabel_3 = QtGui.QLabel(self.listItem_3)
        self.nameLabel_3.setMinimumSize(QtCore.QSize(125, 0))
        self.nameLabel_3.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel_3.setFont(font)
        self.nameLabel_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nameLabel_3.setObjectName(_fromUtf8("nameLabel_3"))
        self.horizontalLayout_5.addWidget(self.nameLabel_3)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.List.addWidget(self.listItem_3)
        self.listItem_6 = QtGui.QWidget(self.centralwidget)
        self.listItem_6.setMinimumSize(QtCore.QSize(0, 0))
        self.listItem_6.setMaximumSize(QtCore.QSize(10000, 100))
        self.listItem_6.setObjectName(_fromUtf8("listItem_6"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.listItem_6)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.nameLabel_7 = QtGui.QLabel(self.listItem_6)
        self.nameLabel_7.setMinimumSize(QtCore.QSize(100, 0))
        self.nameLabel_7.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel_7.setFont(font)
        self.nameLabel_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nameLabel_7.setObjectName(_fromUtf8("nameLabel_7"))
        self.horizontalLayout_7.addWidget(self.nameLabel_7)
        self.nameLabel_8 = QtGui.QLabel(self.listItem_6)
        self.nameLabel_8.setMinimumSize(QtCore.QSize(100, 0))
        self.nameLabel_8.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nameLabel_8.setFont(font)
        self.nameLabel_8.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel_8.setObjectName(_fromUtf8("nameLabel_8"))
        self.horizontalLayout_7.addWidget(self.nameLabel_8)
        self.mEsperaPerfuracaoA = QtGui.QLabel(self.listItem_6)
        self.mEsperaPerfuracaoA.setMinimumSize(QtCore.QSize(100, 0))
        self.mEsperaPerfuracaoA.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.mEsperaPerfuracaoA.setFont(font)
        self.mEsperaPerfuracaoA.setText(_fromUtf8(""))
        self.mEsperaPerfuracaoA.setAlignment(QtCore.Qt.AlignCenter)
        self.mEsperaPerfuracaoA.setObjectName(_fromUtf8("mEsperaPerfuracaoA"))
        self.horizontalLayout_7.addWidget(self.mEsperaPerfuracaoA)
        self.nameLabel_10 = QtGui.QLabel(self.listItem_6)
        self.nameLabel_10.setMinimumSize(QtCore.QSize(125, 0))
        self.nameLabel_10.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nameLabel_10.setFont(font)
        self.nameLabel_10.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel_10.setObjectName(_fromUtf8("nameLabel_10"))
        self.horizontalLayout_7.addWidget(self.nameLabel_10)
        self.utilPerfuracaoA = QtGui.QLabel(self.listItem_6)
        self.utilPerfuracaoA.setMinimumSize(QtCore.QSize(100, 0))
        self.utilPerfuracaoA.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.utilPerfuracaoA.setFont(font)
        self.utilPerfuracaoA.setText(_fromUtf8(""))
        self.utilPerfuracaoA.setAlignment(QtCore.Qt.AlignCenter)
        self.utilPerfuracaoA.setObjectName(_fromUtf8("utilPerfuracaoA"))
        self.horizontalLayout_7.addWidget(self.utilPerfuracaoA)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.List.addWidget(self.listItem_6)
        self.listItem_7 = QtGui.QWidget(self.centralwidget)
        self.listItem_7.setMinimumSize(QtCore.QSize(0, 0))
        self.listItem_7.setMaximumSize(QtCore.QSize(10000, 100))
        self.listItem_7.setObjectName(_fromUtf8("listItem_7"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.listItem_7)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.nameLabel_11 = QtGui.QLabel(self.listItem_7)
        self.nameLabel_11.setMinimumSize(QtCore.QSize(100, 0))
        self.nameLabel_11.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel_11.setFont(font)
        self.nameLabel_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nameLabel_11.setObjectName(_fromUtf8("nameLabel_11"))
        self.horizontalLayout_8.addWidget(self.nameLabel_11)
        self.nameLabel_12 = QtGui.QLabel(self.listItem_7)
        self.nameLabel_12.setMinimumSize(QtCore.QSize(100, 0))
        self.nameLabel_12.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nameLabel_12.setFont(font)
        self.nameLabel_12.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel_12.setObjectName(_fromUtf8("nameLabel_12"))
        self.horizontalLayout_8.addWidget(self.nameLabel_12)
        self.mEsperaPolimentoA = QtGui.QLabel(self.listItem_7)
        self.mEsperaPolimentoA.setMinimumSize(QtCore.QSize(100, 0))
        self.mEsperaPolimentoA.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.mEsperaPolimentoA.setFont(font)
        self.mEsperaPolimentoA.setText(_fromUtf8(""))
        self.mEsperaPolimentoA.setAlignment(QtCore.Qt.AlignCenter)
        self.mEsperaPolimentoA.setObjectName(_fromUtf8("mEsperaPolimentoA"))
        self.horizontalLayout_8.addWidget(self.mEsperaPolimentoA)
        self.nameLabel_14 = QtGui.QLabel(self.listItem_7)
        self.nameLabel_14.setMinimumSize(QtCore.QSize(125, 0))
        self.nameLabel_14.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nameLabel_14.setFont(font)
        self.nameLabel_14.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel_14.setObjectName(_fromUtf8("nameLabel_14"))
        self.horizontalLayout_8.addWidget(self.nameLabel_14)
        self.utilPolimentoA = QtGui.QLabel(self.listItem_7)
        self.utilPolimentoA.setMinimumSize(QtCore.QSize(100, 0))
        self.utilPolimentoA.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.utilPolimentoA.setFont(font)
        self.utilPolimentoA.setText(_fromUtf8(""))
        self.utilPolimentoA.setAlignment(QtCore.Qt.AlignCenter)
        self.utilPolimentoA.setObjectName(_fromUtf8("utilPolimentoA"))
        self.horizontalLayout_8.addWidget(self.utilPolimentoA)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.List.addWidget(self.listItem_7)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setMinimumSize(QtCore.QSize(5, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.line_2.setFont(font)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.List.addWidget(self.line_2)
        self.listItem_4 = QtGui.QWidget(self.centralwidget)
        self.listItem_4.setMinimumSize(QtCore.QSize(0, 0))
        self.listItem_4.setMaximumSize(QtCore.QSize(10000, 100))
        self.listItem_4.setObjectName(_fromUtf8("listItem_4"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.listItem_4)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.nameLabel_4 = QtGui.QLabel(self.listItem_4)
        self.nameLabel_4.setMinimumSize(QtCore.QSize(125, 0))
        self.nameLabel_4.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel_4.setFont(font)
        self.nameLabel_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nameLabel_4.setObjectName(_fromUtf8("nameLabel_4"))
        self.horizontalLayout_6.addWidget(self.nameLabel_4)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.List.addWidget(self.listItem_4)
        self.listItem_9 = QtGui.QWidget(self.centralwidget)
        self.listItem_9.setMinimumSize(QtCore.QSize(0, 0))
        self.listItem_9.setMaximumSize(QtCore.QSize(10000, 100))
        self.listItem_9.setObjectName(_fromUtf8("listItem_9"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.listItem_9)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.nameLabel_36 = QtGui.QLabel(self.listItem_9)
        self.nameLabel_36.setMinimumSize(QtCore.QSize(100, 0))
        self.nameLabel_36.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel_36.setFont(font)
        self.nameLabel_36.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nameLabel_36.setObjectName(_fromUtf8("nameLabel_36"))
        self.horizontalLayout_13.addWidget(self.nameLabel_36)
        self.nameLabel_20 = QtGui.QLabel(self.listItem_9)
        self.nameLabel_20.setMinimumSize(QtCore.QSize(100, 0))
        self.nameLabel_20.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nameLabel_20.setFont(font)
        self.nameLabel_20.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel_20.setObjectName(_fromUtf8("nameLabel_20"))
        self.horizontalLayout_13.addWidget(self.nameLabel_20)
        self.mEsperaPerfuracaoB = QtGui.QLabel(self.listItem_9)
        self.mEsperaPerfuracaoB.setMinimumSize(QtCore.QSize(100, 0))
        self.mEsperaPerfuracaoB.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.mEsperaPerfuracaoB.setFont(font)
        self.mEsperaPerfuracaoB.setText(_fromUtf8(""))
        self.mEsperaPerfuracaoB.setAlignment(QtCore.Qt.AlignCenter)
        self.mEsperaPerfuracaoB.setObjectName(_fromUtf8("mEsperaPerfuracaoB"))
        self.horizontalLayout_13.addWidget(self.mEsperaPerfuracaoB)
        self.nameLabel_38 = QtGui.QLabel(self.listItem_9)
        self.nameLabel_38.setMinimumSize(QtCore.QSize(125, 0))
        self.nameLabel_38.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nameLabel_38.setFont(font)
        self.nameLabel_38.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel_38.setObjectName(_fromUtf8("nameLabel_38"))
        self.horizontalLayout_13.addWidget(self.nameLabel_38)
        self.utilPerfuracaoB = QtGui.QLabel(self.listItem_9)
        self.utilPerfuracaoB.setMinimumSize(QtCore.QSize(100, 0))
        self.utilPerfuracaoB.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.utilPerfuracaoB.setFont(font)
        self.utilPerfuracaoB.setText(_fromUtf8(""))
        self.utilPerfuracaoB.setAlignment(QtCore.Qt.AlignCenter)
        self.utilPerfuracaoB.setObjectName(_fromUtf8("utilPerfuracaoB"))
        self.horizontalLayout_13.addWidget(self.utilPerfuracaoB)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem4)
        self.List.addWidget(self.listItem_9)
        self.listItem_8 = QtGui.QWidget(self.centralwidget)
        self.listItem_8.setMinimumSize(QtCore.QSize(0, 0))
        self.listItem_8.setMaximumSize(QtCore.QSize(10000, 100))
        self.listItem_8.setObjectName(_fromUtf8("listItem_8"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.listItem_8)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.nameLabel_19 = QtGui.QLabel(self.listItem_8)
        self.nameLabel_19.setMinimumSize(QtCore.QSize(100, 0))
        self.nameLabel_19.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel_19.setFont(font)
        self.nameLabel_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nameLabel_19.setObjectName(_fromUtf8("nameLabel_19"))
        self.horizontalLayout_10.addWidget(self.nameLabel_19)
        self.nameLabel_21 = QtGui.QLabel(self.listItem_8)
        self.nameLabel_21.setMinimumSize(QtCore.QSize(100, 0))
        self.nameLabel_21.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nameLabel_21.setFont(font)
        self.nameLabel_21.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel_21.setObjectName(_fromUtf8("nameLabel_21"))
        self.horizontalLayout_10.addWidget(self.nameLabel_21)
        self.mEsperaPolimentoB = QtGui.QLabel(self.listItem_8)
        self.mEsperaPolimentoB.setMinimumSize(QtCore.QSize(100, 0))
        self.mEsperaPolimentoB.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.mEsperaPolimentoB.setFont(font)
        self.mEsperaPolimentoB.setText(_fromUtf8(""))
        self.mEsperaPolimentoB.setAlignment(QtCore.Qt.AlignCenter)
        self.mEsperaPolimentoB.setObjectName(_fromUtf8("mEsperaPolimentoB"))
        self.horizontalLayout_10.addWidget(self.mEsperaPolimentoB)
        self.nameLabel_40 = QtGui.QLabel(self.listItem_8)
        self.nameLabel_40.setMinimumSize(QtCore.QSize(125, 0))
        self.nameLabel_40.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nameLabel_40.setFont(font)
        self.nameLabel_40.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel_40.setObjectName(_fromUtf8("nameLabel_40"))
        self.horizontalLayout_10.addWidget(self.nameLabel_40)
        self.utilPolimentoB = QtGui.QLabel(self.listItem_8)
        self.utilPolimentoB.setMinimumSize(QtCore.QSize(100, 0))
        self.utilPolimentoB.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.utilPolimentoB.setFont(font)
        self.utilPolimentoB.setText(_fromUtf8(""))
        self.utilPolimentoB.setAlignment(QtCore.Qt.AlignCenter)
        self.utilPolimentoB.setObjectName(_fromUtf8("utilPolimentoB"))
        self.horizontalLayout_10.addWidget(self.utilPolimentoB)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.List.addWidget(self.listItem_8)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setMinimumSize(QtCore.QSize(0, 5))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.List.addWidget(self.line)
        self.listItem_11 = QtGui.QWidget(self.centralwidget)
        self.listItem_11.setMinimumSize(QtCore.QSize(0, 0))
        self.listItem_11.setMaximumSize(QtCore.QSize(10000, 100))
        self.listItem_11.setObjectName(_fromUtf8("listItem_11"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.listItem_11)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.nameLabel_23 = QtGui.QLabel(self.listItem_11)
        self.nameLabel_23.setMinimumSize(QtCore.QSize(100, 0))
        self.nameLabel_23.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel_23.setFont(font)
        self.nameLabel_23.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nameLabel_23.setObjectName(_fromUtf8("nameLabel_23"))
        self.horizontalLayout_12.addWidget(self.nameLabel_23)
        self.nameLabel_22 = QtGui.QLabel(self.listItem_11)
        self.nameLabel_22.setMinimumSize(QtCore.QSize(100, 0))
        self.nameLabel_22.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nameLabel_22.setFont(font)
        self.nameLabel_22.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel_22.setObjectName(_fromUtf8("nameLabel_22"))
        self.horizontalLayout_12.addWidget(self.nameLabel_22)
        self.mEsperaEnvernizamento = QtGui.QLabel(self.listItem_11)
        self.mEsperaEnvernizamento.setMinimumSize(QtCore.QSize(100, 0))
        self.mEsperaEnvernizamento.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.mEsperaEnvernizamento.setFont(font)
        self.mEsperaEnvernizamento.setText(_fromUtf8(""))
        self.mEsperaEnvernizamento.setAlignment(QtCore.Qt.AlignCenter)
        self.mEsperaEnvernizamento.setObjectName(_fromUtf8("mEsperaEnvernizamento"))
        self.horizontalLayout_12.addWidget(self.mEsperaEnvernizamento)
        self.nameLabel_46 = QtGui.QLabel(self.listItem_11)
        self.nameLabel_46.setMinimumSize(QtCore.QSize(125, 0))
        self.nameLabel_46.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nameLabel_46.setFont(font)
        self.nameLabel_46.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel_46.setObjectName(_fromUtf8("nameLabel_46"))
        self.horizontalLayout_12.addWidget(self.nameLabel_46)
        self.utilEnvernizamento = QtGui.QLabel(self.listItem_11)
        self.utilEnvernizamento.setMinimumSize(QtCore.QSize(100, 0))
        self.utilEnvernizamento.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.utilEnvernizamento.setFont(font)
        self.utilEnvernizamento.setText(_fromUtf8(""))
        self.utilEnvernizamento.setAlignment(QtCore.Qt.AlignCenter)
        self.utilEnvernizamento.setObjectName(_fromUtf8("utilEnvernizamento"))
        self.horizontalLayout_12.addWidget(self.utilEnvernizamento)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem6)
        self.List.addWidget(self.listItem_11)
        self.verticalLayout_4.addLayout(self.List)
        self.footer = QtGui.QWidget(self.centralwidget)
        self.footer.setMaximumSize(QtCore.QSize(100000, 50))
        self.footer.setObjectName(_fromUtf8("footer"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.footer)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.nameLabel_30 = QtGui.QLabel(self.footer)
        self.nameLabel_30.setMinimumSize(QtCore.QSize(115, 0))
        self.nameLabel_30.setMaximumSize(QtCore.QSize(115, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel_30.setFont(font)
        self.nameLabel_30.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nameLabel_30.setObjectName(_fromUtf8("nameLabel_30"))
        self.horizontalLayout.addWidget(self.nameLabel_30)
        self.clientesAtendidos = QtGui.QLabel(self.footer)
        self.clientesAtendidos.setMinimumSize(QtCore.QSize(100, 0))
        self.clientesAtendidos.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.clientesAtendidos.setFont(font)
        self.clientesAtendidos.setText(_fromUtf8(""))
        self.clientesAtendidos.setAlignment(QtCore.Qt.AlignCenter)
        self.clientesAtendidos.setObjectName(_fromUtf8("clientesAtendidos"))
        self.horizontalLayout.addWidget(self.clientesAtendidos)
        self.nameLabel_29 = QtGui.QLabel(self.footer)
        self.nameLabel_29.setMinimumSize(QtCore.QSize(100, 0))
        self.nameLabel_29.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel_29.setFont(font)
        self.nameLabel_29.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel_29.setObjectName(_fromUtf8("nameLabel_29"))
        self.horizontalLayout.addWidget(self.nameLabel_29)
        self.nRepeticoes = QtGui.QLabel(self.footer)
        self.nRepeticoes.setMinimumSize(QtCore.QSize(100, 0))
        self.nRepeticoes.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nRepeticoes.setFont(font)
        self.nRepeticoes.setText(_fromUtf8(""))
        self.nRepeticoes.setAlignment(QtCore.Qt.AlignCenter)
        self.nRepeticoes.setObjectName(_fromUtf8("nRepeticoes"))
        self.horizontalLayout.addWidget(self.nRepeticoes)
        self.nameLabel_28 = QtGui.QLabel(self.footer)
        self.nameLabel_28.setMinimumSize(QtCore.QSize(115, 0))
        self.nameLabel_28.setMaximumSize(QtCore.QSize(115, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel_28.setFont(font)
        self.nameLabel_28.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel_28.setObjectName(_fromUtf8("nameLabel_28"))
        self.horizontalLayout.addWidget(self.nameLabel_28)
        self.tempoSimulacao = QtGui.QLabel(self.footer)
        self.tempoSimulacao.setMinimumSize(QtCore.QSize(100, 0))
        self.tempoSimulacao.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tempoSimulacao.setFont(font)
        self.tempoSimulacao.setText(_fromUtf8(""))
        self.tempoSimulacao.setAlignment(QtCore.Qt.AlignCenter)
        self.tempoSimulacao.setObjectName(_fromUtf8("tempoSimulacao"))
        self.horizontalLayout.addWidget(self.tempoSimulacao)
        self.verticalLayout_4.addWidget(self.footer)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Resultados da simulaçao", None))
        self.nameLabel_3.setText(_translate("MainWindow", "Peças grandes (A)", None))
        self.nameLabel_7.setText(_translate("MainWindow", "Perfuraçao", None))
        self.nameLabel_8.setText(_translate("MainWindow", "Media espera", None))
        self.nameLabel_10.setText(_translate("MainWindow", "Utilizacao media", None))
        self.nameLabel_11.setText(_translate("MainWindow", "Polimento", None))
        self.nameLabel_12.setText(_translate("MainWindow", "Media espera", None))
        self.nameLabel_14.setText(_translate("MainWindow", "Utilizacao media", None))
        self.nameLabel_4.setText(_translate("MainWindow", "Peças grandes (B)", None))
        self.nameLabel_36.setText(_translate("MainWindow", "Perfuraçao", None))
        self.nameLabel_20.setText(_translate("MainWindow", "Media espera", None))
        self.nameLabel_38.setText(_translate("MainWindow", "Utilizacao media", None))
        self.nameLabel_19.setText(_translate("MainWindow", "Polimento", None))
        self.nameLabel_21.setText(_translate("MainWindow", "Media espera", None))
        self.nameLabel_40.setText(_translate("MainWindow", "Utilizacao media", None))
        self.nameLabel_23.setText(_translate("MainWindow", "Envernizamento", None))
        self.nameLabel_22.setText(_translate("MainWindow", "Media espera", None))
        self.nameLabel_46.setText(_translate("MainWindow", "Utilizacao media", None))
        self.nameLabel_30.setText(_translate("MainWindow", "Clientes atendidos", None))
        self.nameLabel_29.setText(_translate("MainWindow", "Nº Repeticoes", None))
        self.nameLabel_28.setText(_translate("MainWindow", "Tempo simulacao", None))

