# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'outputWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(855, 471)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.List = QtGui.QVBoxLayout()
        self.List.setObjectName(_fromUtf8("List"))
        self.listItem_3 = QtGui.QWidget(self.centralwidget)
        self.listItem_3.setMinimumSize(QtCore.QSize(0, 0))
        self.listItem_3.setMaximumSize(QtCore.QSize(10000, 100))
        self.listItem_3.setObjectName(_fromUtf8("listItem_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.listItem_3)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.nameLabel_3 = QtGui.QLabel(self.listItem_3)
        self.nameLabel_3.setMinimumSize(QtCore.QSize(125, 0))
        self.nameLabel_3.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel_3.setFont(font)
        self.nameLabel_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nameLabel_3.setObjectName(_fromUtf8("nameLabel_3"))
        self.horizontalLayout_5.addWidget(self.nameLabel_3)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.List.addWidget(self.listItem_3)
        self.listItem_6 = QtGui.QWidget(self.centralwidget)
        self.listItem_6.setMinimumSize(QtCore.QSize(0, 0))
        self.listItem_6.setMaximumSize(QtCore.QSize(10000, 100))
        self.listItem_6.setObjectName(_fromUtf8("listItem_6"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.listItem_6)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.nameLabel_7 = QtGui.QLabel(self.listItem_6)
        self.nameLabel_7.setMinimumSize(QtCore.QSize(125, 0))
        self.nameLabel_7.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel_7.setFont(font)
        self.nameLabel_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nameLabel_7.setObjectName(_fromUtf8("nameLabel_7"))
        self.horizontalLayout_7.addWidget(self.nameLabel_7)
        self.nameLabel_8 = QtGui.QLabel(self.listItem_6)
        self.nameLabel_8.setMinimumSize(QtCore.QSize(100, 0))
        self.nameLabel_8.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nameLabel_8.setFont(font)
        self.nameLabel_8.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel_8.setObjectName(_fromUtf8("nameLabel_8"))
        self.horizontalLayout_7.addWidget(self.nameLabel_8)
        self.mEsperaPerfuracaoA = QtGui.QLabel(self.listItem_6)
        self.mEsperaPerfuracaoA.setMinimumSize(QtCore.QSize(100, 0))
        self.mEsperaPerfuracaoA.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.mEsperaPerfuracaoA.setFont(font)
        self.mEsperaPerfuracaoA.setText(_fromUtf8(""))
        self.mEsperaPerfuracaoA.setAlignment(QtCore.Qt.AlignCenter)
        self.mEsperaPerfuracaoA.setObjectName(_fromUtf8("mEsperaPerfuracaoA"))
        self.horizontalLayout_7.addWidget(self.mEsperaPerfuracaoA)
        self.nameLabel_10 = QtGui.QLabel(self.listItem_6)
        self.nameLabel_10.setMinimumSize(QtCore.QSize(125, 0))
        self.nameLabel_10.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nameLabel_10.setFont(font)
        self.nameLabel_10.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel_10.setObjectName(_fromUtf8("nameLabel_10"))
        self.horizontalLayout_7.addWidget(self.nameLabel_10)
        self.utilPerfuracaoA = QtGui.QLabel(self.listItem_6)
        self.utilPerfuracaoA.setMinimumSize(QtCore.QSize(100, 0))
        self.utilPerfuracaoA.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.utilPerfuracaoA.setFont(font)
        self.utilPerfuracaoA.setText(_fromUtf8(""))
        self.utilPerfuracaoA.setAlignment(QtCore.Qt.AlignCenter)
        self.utilPerfuracaoA.setObjectName(_fromUtf8("utilPerfuracaoA"))
        self.horizontalLayout_7.addWidget(self.utilPerfuracaoA)
        self.nameLabel_13 = QtGui.QLabel(self.listItem_6)
        self.nameLabel_13.setMinimumSize(QtCore.QSize(125, 0))
        self.nameLabel_13.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nameLabel_13.setFont(font)
        self.nameLabel_13.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel_13.setObjectName(_fromUtf8("nameLabel_13"))
        self.horizontalLayout_7.addWidget(self.nameLabel_13)
        self.compPerfuracaoA = QtGui.QLabel(self.listItem_6)
        self.compPerfuracaoA.setMinimumSize(QtCore.QSize(100, 0))
        self.compPerfuracaoA.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.compPerfuracaoA.setFont(font)
        self.compPerfuracaoA.setText(_fromUtf8(""))
        self.compPerfuracaoA.setAlignment(QtCore.Qt.AlignCenter)
        self.compPerfuracaoA.setObjectName(_fromUtf8("compPerfuracaoA"))
        self.horizontalLayout_7.addWidget(self.compPerfuracaoA)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.List.addWidget(self.listItem_6)
        self.listItem_7 = QtGui.QWidget(self.centralwidget)
        self.listItem_7.setMinimumSize(QtCore.QSize(0, 0))
        self.listItem_7.setMaximumSize(QtCore.QSize(10000, 100))
        self.listItem_7.setObjectName(_fromUtf8("listItem_7"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.listItem_7)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.nameLabel_11 = QtGui.QLabel(self.listItem_7)
        self.nameLabel_11.setMinimumSize(QtCore.QSize(125, 0))
        self.nameLabel_11.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel_11.setFont(font)
        self.nameLabel_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nameLabel_11.setObjectName(_fromUtf8("nameLabel_11"))
        self.horizontalLayout_8.addWidget(self.nameLabel_11)
        self.nameLabel_12 = QtGui.QLabel(self.listItem_7)
        self.nameLabel_12.setMinimumSize(QtCore.QSize(100, 0))
        self.nameLabel_12.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nameLabel_12.setFont(font)
        self.nameLabel_12.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel_12.setObjectName(_fromUtf8("nameLabel_12"))
        self.horizontalLayout_8.addWidget(self.nameLabel_12)
        self.mEsperaPolimentoA = QtGui.QLabel(self.listItem_7)
        self.mEsperaPolimentoA.setMinimumSize(QtCore.QSize(100, 0))
        self.mEsperaPolimentoA.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.mEsperaPolimentoA.setFont(font)
        self.mEsperaPolimentoA.setText(_fromUtf8(""))
        self.mEsperaPolimentoA.setAlignment(QtCore.Qt.AlignCenter)
        self.mEsperaPolimentoA.setObjectName(_fromUtf8("mEsperaPolimentoA"))
        self.horizontalLayout_8.addWidget(self.mEsperaPolimentoA)
        self.nameLabel_14 = QtGui.QLabel(self.listItem_7)
        self.nameLabel_14.setMinimumSize(QtCore.QSize(125, 0))
        self.nameLabel_14.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nameLabel_14.setFont(font)
        self.nameLabel_14.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel_14.setObjectName(_fromUtf8("nameLabel_14"))
        self.horizontalLayout_8.addWidget(self.nameLabel_14)
        self.utilPolimentoA = QtGui.QLabel(self.listItem_7)
        self.utilPolimentoA.setMinimumSize(QtCore.QSize(100, 0))
        self.utilPolimentoA.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.utilPolimentoA.setFont(font)
        self.utilPolimentoA.setText(_fromUtf8(""))
        self.utilPolimentoA.setAlignment(QtCore.Qt.AlignCenter)
        self.utilPolimentoA.setObjectName(_fromUtf8("utilPolimentoA"))
        self.horizontalLayout_8.addWidget(self.utilPolimentoA)
        self.nameLabel_15 = QtGui.QLabel(self.listItem_7)
        self.nameLabel_15.setMinimumSize(QtCore.QSize(125, 0))
        self.nameLabel_15.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nameLabel_15.setFont(font)
        self.nameLabel_15.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel_15.setObjectName(_fromUtf8("nameLabel_15"))
        self.horizontalLayout_8.addWidget(self.nameLabel_15)
        self.compPolimentoA = QtGui.QLabel(self.listItem_7)
        self.compPolimentoA.setMinimumSize(QtCore.QSize(100, 0))
        self.compPolimentoA.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.compPolimentoA.setFont(font)
        self.compPolimentoA.setText(_fromUtf8(""))
        self.compPolimentoA.setAlignment(QtCore.Qt.AlignCenter)
        self.compPolimentoA.setObjectName(_fromUtf8("compPolimentoA"))
        self.horizontalLayout_8.addWidget(self.compPolimentoA)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.List.addWidget(self.listItem_7)
        self.listItem_10 = QtGui.QWidget(self.centralwidget)
        self.listItem_10.setMinimumSize(QtCore.QSize(0, 0))
        self.listItem_10.setMaximumSize(QtCore.QSize(10000, 100))
        self.listItem_10.setObjectName(_fromUtf8("listItem_10"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.listItem_10)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.nameLabel_24 = QtGui.QLabel(self.listItem_10)
        self.nameLabel_24.setMinimumSize(QtCore.QSize(125, 0))
        self.nameLabel_24.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel_24.setFont(font)
        self.nameLabel_24.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nameLabel_24.setObjectName(_fromUtf8("nameLabel_24"))
        self.horizontalLayout_9.addWidget(self.nameLabel_24)
        self.nameLabel_25 = QtGui.QLabel(self.listItem_10)
        self.nameLabel_25.setMinimumSize(QtCore.QSize(100, 0))
        self.nameLabel_25.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nameLabel_25.setFont(font)
        self.nameLabel_25.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel_25.setObjectName(_fromUtf8("nameLabel_25"))
        self.horizontalLayout_9.addWidget(self.nameLabel_25)
        self.atendidosPerfuracaoA = QtGui.QLabel(self.listItem_10)
        self.atendidosPerfuracaoA.setMinimumSize(QtCore.QSize(100, 0))
        self.atendidosPerfuracaoA.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.atendidosPerfuracaoA.setFont(font)
        self.atendidosPerfuracaoA.setText(_fromUtf8(""))
        self.atendidosPerfuracaoA.setAlignment(QtCore.Qt.AlignCenter)
        self.atendidosPerfuracaoA.setObjectName(_fromUtf8("atendidosPerfuracaoA"))
        self.horizontalLayout_9.addWidget(self.atendidosPerfuracaoA)
        self.nameLabel_26 = QtGui.QLabel(self.listItem_10)
        self.nameLabel_26.setMinimumSize(QtCore.QSize(125, 0))
        self.nameLabel_26.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nameLabel_26.setFont(font)
        self.nameLabel_26.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel_26.setObjectName(_fromUtf8("nameLabel_26"))
        self.horizontalLayout_9.addWidget(self.nameLabel_26)
        self.atendidosPolimentoA = QtGui.QLabel(self.listItem_10)
        self.atendidosPolimentoA.setMinimumSize(QtCore.QSize(100, 0))
        self.atendidosPolimentoA.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.atendidosPolimentoA.setFont(font)
        self.atendidosPolimentoA.setText(_fromUtf8(""))
        self.atendidosPolimentoA.setAlignment(QtCore.Qt.AlignCenter)
        self.atendidosPolimentoA.setObjectName(_fromUtf8("atendidosPolimentoA"))
        self.horizontalLayout_9.addWidget(self.atendidosPolimentoA)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.List.addWidget(self.listItem_10)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setMinimumSize(QtCore.QSize(5, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.line_2.setFont(font)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.List.addWidget(self.line_2)
        self.listItem_4 = QtGui.QWidget(self.centralwidget)
        self.listItem_4.setMinimumSize(QtCore.QSize(0, 0))
        self.listItem_4.setMaximumSize(QtCore.QSize(10000, 100))
        self.listItem_4.setObjectName(_fromUtf8("listItem_4"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.listItem_4)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.nameLabel_4 = QtGui.QLabel(self.listItem_4)
        self.nameLabel_4.setMinimumSize(QtCore.QSize(125, 0))
        self.nameLabel_4.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel_4.setFont(font)
        self.nameLabel_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nameLabel_4.setObjectName(_fromUtf8("nameLabel_4"))
        self.horizontalLayout_6.addWidget(self.nameLabel_4)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.List.addWidget(self.listItem_4)
        self.listItem_9 = QtGui.QWidget(self.centralwidget)
        self.listItem_9.setMinimumSize(QtCore.QSize(0, 0))
        self.listItem_9.setMaximumSize(QtCore.QSize(10000, 100))
        self.listItem_9.setObjectName(_fromUtf8("listItem_9"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.listItem_9)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.nameLabel_36 = QtGui.QLabel(self.listItem_9)
        self.nameLabel_36.setMinimumSize(QtCore.QSize(125, 0))
        self.nameLabel_36.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel_36.setFont(font)
        self.nameLabel_36.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nameLabel_36.setObjectName(_fromUtf8("nameLabel_36"))
        self.horizontalLayout_13.addWidget(self.nameLabel_36)
        self.nameLabel_20 = QtGui.QLabel(self.listItem_9)
        self.nameLabel_20.setMinimumSize(QtCore.QSize(100, 0))
        self.nameLabel_20.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nameLabel_20.setFont(font)
        self.nameLabel_20.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel_20.setObjectName(_fromUtf8("nameLabel_20"))
        self.horizontalLayout_13.addWidget(self.nameLabel_20)
        self.mEsperaPerfuracaoB = QtGui.QLabel(self.listItem_9)
        self.mEsperaPerfuracaoB.setMinimumSize(QtCore.QSize(100, 0))
        self.mEsperaPerfuracaoB.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.mEsperaPerfuracaoB.setFont(font)
        self.mEsperaPerfuracaoB.setText(_fromUtf8(""))
        self.mEsperaPerfuracaoB.setAlignment(QtCore.Qt.AlignCenter)
        self.mEsperaPerfuracaoB.setObjectName(_fromUtf8("mEsperaPerfuracaoB"))
        self.horizontalLayout_13.addWidget(self.mEsperaPerfuracaoB)
        self.nameLabel_38 = QtGui.QLabel(self.listItem_9)
        self.nameLabel_38.setMinimumSize(QtCore.QSize(125, 0))
        self.nameLabel_38.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nameLabel_38.setFont(font)
        self.nameLabel_38.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel_38.setObjectName(_fromUtf8("nameLabel_38"))
        self.horizontalLayout_13.addWidget(self.nameLabel_38)
        self.utilPerfuracaoB = QtGui.QLabel(self.listItem_9)
        self.utilPerfuracaoB.setMinimumSize(QtCore.QSize(100, 0))
        self.utilPerfuracaoB.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.utilPerfuracaoB.setFont(font)
        self.utilPerfuracaoB.setText(_fromUtf8(""))
        self.utilPerfuracaoB.setAlignment(QtCore.Qt.AlignCenter)
        self.utilPerfuracaoB.setObjectName(_fromUtf8("utilPerfuracaoB"))
        self.horizontalLayout_13.addWidget(self.utilPerfuracaoB)
        self.nameLabel_16 = QtGui.QLabel(self.listItem_9)
        self.nameLabel_16.setMinimumSize(QtCore.QSize(125, 0))
        self.nameLabel_16.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nameLabel_16.setFont(font)
        self.nameLabel_16.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel_16.setObjectName(_fromUtf8("nameLabel_16"))
        self.horizontalLayout_13.addWidget(self.nameLabel_16)
        self.compPerfuracaoB = QtGui.QLabel(self.listItem_9)
        self.compPerfuracaoB.setMinimumSize(QtCore.QSize(100, 0))
        self.compPerfuracaoB.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.compPerfuracaoB.setFont(font)
        self.compPerfuracaoB.setText(_fromUtf8(""))
        self.compPerfuracaoB.setAlignment(QtCore.Qt.AlignCenter)
        self.compPerfuracaoB.setObjectName(_fromUtf8("compPerfuracaoB"))
        self.horizontalLayout_13.addWidget(self.compPerfuracaoB)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem5)
        self.List.addWidget(self.listItem_9)
        self.listItem_8 = QtGui.QWidget(self.centralwidget)
        self.listItem_8.setMinimumSize(QtCore.QSize(0, 0))
        self.listItem_8.setMaximumSize(QtCore.QSize(10000, 100))
        self.listItem_8.setObjectName(_fromUtf8("listItem_8"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.listItem_8)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.nameLabel_19 = QtGui.QLabel(self.listItem_8)
        self.nameLabel_19.setMinimumSize(QtCore.QSize(125, 0))
        self.nameLabel_19.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel_19.setFont(font)
        self.nameLabel_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nameLabel_19.setObjectName(_fromUtf8("nameLabel_19"))
        self.horizontalLayout_10.addWidget(self.nameLabel_19)
        self.nameLabel_21 = QtGui.QLabel(self.listItem_8)
        self.nameLabel_21.setMinimumSize(QtCore.QSize(100, 0))
        self.nameLabel_21.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nameLabel_21.setFont(font)
        self.nameLabel_21.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel_21.setObjectName(_fromUtf8("nameLabel_21"))
        self.horizontalLayout_10.addWidget(self.nameLabel_21)
        self.mEsperaPolimentoB = QtGui.QLabel(self.listItem_8)
        self.mEsperaPolimentoB.setMinimumSize(QtCore.QSize(100, 0))
        self.mEsperaPolimentoB.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.mEsperaPolimentoB.setFont(font)
        self.mEsperaPolimentoB.setText(_fromUtf8(""))
        self.mEsperaPolimentoB.setAlignment(QtCore.Qt.AlignCenter)
        self.mEsperaPolimentoB.setObjectName(_fromUtf8("mEsperaPolimentoB"))
        self.horizontalLayout_10.addWidget(self.mEsperaPolimentoB)
        self.nameLabel_40 = QtGui.QLabel(self.listItem_8)
        self.nameLabel_40.setMinimumSize(QtCore.QSize(125, 0))
        self.nameLabel_40.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nameLabel_40.setFont(font)
        self.nameLabel_40.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel_40.setObjectName(_fromUtf8("nameLabel_40"))
        self.horizontalLayout_10.addWidget(self.nameLabel_40)
        self.utilPolimentoB = QtGui.QLabel(self.listItem_8)
        self.utilPolimentoB.setMinimumSize(QtCore.QSize(100, 0))
        self.utilPolimentoB.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.utilPolimentoB.setFont(font)
        self.utilPolimentoB.setText(_fromUtf8(""))
        self.utilPolimentoB.setAlignment(QtCore.Qt.AlignCenter)
        self.utilPolimentoB.setObjectName(_fromUtf8("utilPolimentoB"))
        self.horizontalLayout_10.addWidget(self.utilPolimentoB)
        self.nameLabel_17 = QtGui.QLabel(self.listItem_8)
        self.nameLabel_17.setMinimumSize(QtCore.QSize(125, 0))
        self.nameLabel_17.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nameLabel_17.setFont(font)
        self.nameLabel_17.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel_17.setObjectName(_fromUtf8("nameLabel_17"))
        self.horizontalLayout_10.addWidget(self.nameLabel_17)
        self.compPolimentoB = QtGui.QLabel(self.listItem_8)
        self.compPolimentoB.setMinimumSize(QtCore.QSize(100, 0))
        self.compPolimentoB.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.compPolimentoB.setFont(font)
        self.compPolimentoB.setText(_fromUtf8(""))
        self.compPolimentoB.setAlignment(QtCore.Qt.AlignCenter)
        self.compPolimentoB.setObjectName(_fromUtf8("compPolimentoB"))
        self.horizontalLayout_10.addWidget(self.compPolimentoB)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem6)
        self.List.addWidget(self.listItem_8)
        self.listItem_12 = QtGui.QWidget(self.centralwidget)
        self.listItem_12.setMinimumSize(QtCore.QSize(0, 0))
        self.listItem_12.setMaximumSize(QtCore.QSize(10000, 100))
        self.listItem_12.setObjectName(_fromUtf8("listItem_12"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.listItem_12)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.nameLabel_32 = QtGui.QLabel(self.listItem_12)
        self.nameLabel_32.setMinimumSize(QtCore.QSize(125, 0))
        self.nameLabel_32.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel_32.setFont(font)
        self.nameLabel_32.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nameLabel_32.setObjectName(_fromUtf8("nameLabel_32"))
        self.horizontalLayout_14.addWidget(self.nameLabel_32)
        self.nameLabel_33 = QtGui.QLabel(self.listItem_12)
        self.nameLabel_33.setMinimumSize(QtCore.QSize(100, 0))
        self.nameLabel_33.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nameLabel_33.setFont(font)
        self.nameLabel_33.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel_33.setObjectName(_fromUtf8("nameLabel_33"))
        self.horizontalLayout_14.addWidget(self.nameLabel_33)
        self.atendidosPerfuracaoB = QtGui.QLabel(self.listItem_12)
        self.atendidosPerfuracaoB.setMinimumSize(QtCore.QSize(100, 0))
        self.atendidosPerfuracaoB.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.atendidosPerfuracaoB.setFont(font)
        self.atendidosPerfuracaoB.setText(_fromUtf8(""))
        self.atendidosPerfuracaoB.setAlignment(QtCore.Qt.AlignCenter)
        self.atendidosPerfuracaoB.setObjectName(_fromUtf8("atendidosPerfuracaoB"))
        self.horizontalLayout_14.addWidget(self.atendidosPerfuracaoB)
        self.nameLabel_34 = QtGui.QLabel(self.listItem_12)
        self.nameLabel_34.setMinimumSize(QtCore.QSize(125, 0))
        self.nameLabel_34.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nameLabel_34.setFont(font)
        self.nameLabel_34.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel_34.setObjectName(_fromUtf8("nameLabel_34"))
        self.horizontalLayout_14.addWidget(self.nameLabel_34)
        self.atendidosPolimentoB = QtGui.QLabel(self.listItem_12)
        self.atendidosPolimentoB.setMinimumSize(QtCore.QSize(100, 0))
        self.atendidosPolimentoB.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.atendidosPolimentoB.setFont(font)
        self.atendidosPolimentoB.setText(_fromUtf8(""))
        self.atendidosPolimentoB.setAlignment(QtCore.Qt.AlignCenter)
        self.atendidosPolimentoB.setObjectName(_fromUtf8("atendidosPolimentoB"))
        self.horizontalLayout_14.addWidget(self.atendidosPolimentoB)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem7)
        self.List.addWidget(self.listItem_12)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setMinimumSize(QtCore.QSize(0, 5))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.List.addWidget(self.line)
        self.listItem_11 = QtGui.QWidget(self.centralwidget)
        self.listItem_11.setMinimumSize(QtCore.QSize(0, 0))
        self.listItem_11.setMaximumSize(QtCore.QSize(10000, 100))
        self.listItem_11.setObjectName(_fromUtf8("listItem_11"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.listItem_11)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.nameLabel_23 = QtGui.QLabel(self.listItem_11)
        self.nameLabel_23.setMinimumSize(QtCore.QSize(125, 0))
        self.nameLabel_23.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel_23.setFont(font)
        self.nameLabel_23.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nameLabel_23.setObjectName(_fromUtf8("nameLabel_23"))
        self.horizontalLayout_12.addWidget(self.nameLabel_23)
        self.nameLabel_22 = QtGui.QLabel(self.listItem_11)
        self.nameLabel_22.setMinimumSize(QtCore.QSize(100, 0))
        self.nameLabel_22.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nameLabel_22.setFont(font)
        self.nameLabel_22.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel_22.setObjectName(_fromUtf8("nameLabel_22"))
        self.horizontalLayout_12.addWidget(self.nameLabel_22)
        self.mEsperaEnvernizamento = QtGui.QLabel(self.listItem_11)
        self.mEsperaEnvernizamento.setMinimumSize(QtCore.QSize(100, 0))
        self.mEsperaEnvernizamento.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.mEsperaEnvernizamento.setFont(font)
        self.mEsperaEnvernizamento.setText(_fromUtf8(""))
        self.mEsperaEnvernizamento.setAlignment(QtCore.Qt.AlignCenter)
        self.mEsperaEnvernizamento.setObjectName(_fromUtf8("mEsperaEnvernizamento"))
        self.horizontalLayout_12.addWidget(self.mEsperaEnvernizamento)
        self.nameLabel_46 = QtGui.QLabel(self.listItem_11)
        self.nameLabel_46.setMinimumSize(QtCore.QSize(125, 0))
        self.nameLabel_46.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nameLabel_46.setFont(font)
        self.nameLabel_46.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel_46.setObjectName(_fromUtf8("nameLabel_46"))
        self.horizontalLayout_12.addWidget(self.nameLabel_46)
        self.utilEnvernizamento = QtGui.QLabel(self.listItem_11)
        self.utilEnvernizamento.setMinimumSize(QtCore.QSize(100, 0))
        self.utilEnvernizamento.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.utilEnvernizamento.setFont(font)
        self.utilEnvernizamento.setText(_fromUtf8(""))
        self.utilEnvernizamento.setAlignment(QtCore.Qt.AlignCenter)
        self.utilEnvernizamento.setObjectName(_fromUtf8("utilEnvernizamento"))
        self.horizontalLayout_12.addWidget(self.utilEnvernizamento)
        self.nameLabel_18 = QtGui.QLabel(self.listItem_11)
        self.nameLabel_18.setMinimumSize(QtCore.QSize(125, 0))
        self.nameLabel_18.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nameLabel_18.setFont(font)
        self.nameLabel_18.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel_18.setObjectName(_fromUtf8("nameLabel_18"))
        self.horizontalLayout_12.addWidget(self.nameLabel_18)
        self.compEnvernizamento = QtGui.QLabel(self.listItem_11)
        self.compEnvernizamento.setMinimumSize(QtCore.QSize(100, 0))
        self.compEnvernizamento.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.compEnvernizamento.setFont(font)
        self.compEnvernizamento.setText(_fromUtf8(""))
        self.compEnvernizamento.setAlignment(QtCore.Qt.AlignCenter)
        self.compEnvernizamento.setObjectName(_fromUtf8("compEnvernizamento"))
        self.horizontalLayout_12.addWidget(self.compEnvernizamento)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem8)
        self.List.addWidget(self.listItem_11)
        self.verticalLayout_4.addLayout(self.List)
        self.footer = QtGui.QWidget(self.centralwidget)
        self.footer.setMaximumSize(QtCore.QSize(100000, 50))
        self.footer.setObjectName(_fromUtf8("footer"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.footer)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.nameLabel_30 = QtGui.QLabel(self.footer)
        self.nameLabel_30.setMinimumSize(QtCore.QSize(115, 0))
        self.nameLabel_30.setMaximumSize(QtCore.QSize(115, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel_30.setFont(font)
        self.nameLabel_30.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nameLabel_30.setObjectName(_fromUtf8("nameLabel_30"))
        self.horizontalLayout.addWidget(self.nameLabel_30)
        self.clientesAtendidos = QtGui.QLabel(self.footer)
        self.clientesAtendidos.setMinimumSize(QtCore.QSize(100, 0))
        self.clientesAtendidos.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.clientesAtendidos.setFont(font)
        self.clientesAtendidos.setText(_fromUtf8(""))
        self.clientesAtendidos.setAlignment(QtCore.Qt.AlignCenter)
        self.clientesAtendidos.setObjectName(_fromUtf8("clientesAtendidos"))
        self.horizontalLayout.addWidget(self.clientesAtendidos)
        self.nameLabel_28 = QtGui.QLabel(self.footer)
        self.nameLabel_28.setMinimumSize(QtCore.QSize(115, 0))
        self.nameLabel_28.setMaximumSize(QtCore.QSize(115, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel_28.setFont(font)
        self.nameLabel_28.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel_28.setObjectName(_fromUtf8("nameLabel_28"))
        self.horizontalLayout.addWidget(self.nameLabel_28)
        self.tempoSimulacao = QtGui.QLabel(self.footer)
        self.tempoSimulacao.setMinimumSize(QtCore.QSize(100, 0))
        self.tempoSimulacao.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tempoSimulacao.setFont(font)
        self.tempoSimulacao.setText(_fromUtf8(""))
        self.tempoSimulacao.setAlignment(QtCore.Qt.AlignCenter)
        self.tempoSimulacao.setObjectName(_fromUtf8("tempoSimulacao"))
        self.horizontalLayout.addWidget(self.tempoSimulacao)
        self.nameLabel_35 = QtGui.QLabel(self.footer)
        self.nameLabel_35.setMinimumSize(QtCore.QSize(115, 0))
        self.nameLabel_35.setMaximumSize(QtCore.QSize(115, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel_35.setFont(font)
        self.nameLabel_35.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel_35.setObjectName(_fromUtf8("nameLabel_35"))
        self.horizontalLayout.addWidget(self.nameLabel_35)
        self.nRepeticoes = QtGui.QLabel(self.footer)
        self.nRepeticoes.setMinimumSize(QtCore.QSize(100, 0))
        self.nRepeticoes.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nRepeticoes.setFont(font)
        self.nRepeticoes.setText(_fromUtf8(""))
        self.nRepeticoes.setAlignment(QtCore.Qt.AlignCenter)
        self.nRepeticoes.setObjectName(_fromUtf8("nRepeticoes"))
        self.horizontalLayout.addWidget(self.nRepeticoes)
        self.verticalLayout_4.addWidget(self.footer)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Resultados da simulaçao", None))
        self.nameLabel_3.setText(_translate("MainWindow", "Peças grandes (A)", None))
        self.nameLabel_7.setText(_translate("MainWindow", "Perfuraçao", None))
        self.nameLabel_8.setText(_translate("MainWindow", "Media espera", None))
        self.nameLabel_10.setText(_translate("MainWindow", "Utilizacao media", None))
        self.nameLabel_13.setText(_translate("MainWindow", "Comp medio fila", None))
        self.nameLabel_11.setText(_translate("MainWindow", "Polimento", None))
        self.nameLabel_12.setText(_translate("MainWindow", "Media espera", None))
        self.nameLabel_14.setText(_translate("MainWindow", "Utilizacao media", None))
        self.nameLabel_15.setText(_translate("MainWindow", "Comp medio fila", None))
        self.nameLabel_24.setText(_translate("MainWindow", "Clientes atendidos", None))
        self.nameLabel_25.setText(_translate("MainWindow", "Perfuracao", None))
        self.nameLabel_26.setText(_translate("MainWindow", "Polimento", None))
        self.nameLabel_4.setText(_translate("MainWindow", "Peças grandes (B)", None))
        self.nameLabel_36.setText(_translate("MainWindow", "Perfuraçao", None))
        self.nameLabel_20.setText(_translate("MainWindow", "Media espera", None))
        self.nameLabel_38.setText(_translate("MainWindow", "Utilizacao media", None))
        self.nameLabel_16.setText(_translate("MainWindow", "Comp medio fila", None))
        self.nameLabel_19.setText(_translate("MainWindow", "Polimento", None))
        self.nameLabel_21.setText(_translate("MainWindow", "Media espera", None))
        self.nameLabel_40.setText(_translate("MainWindow", "Utilizacao media", None))
        self.nameLabel_17.setText(_translate("MainWindow", "Comp medio fila", None))
        self.nameLabel_32.setText(_translate("MainWindow", "Clientes atendidos", None))
        self.nameLabel_33.setText(_translate("MainWindow", "Perfuracao", None))
        self.nameLabel_34.setText(_translate("MainWindow", "Polimento", None))
        self.nameLabel_23.setText(_translate("MainWindow", "Envernizamento", None))
        self.nameLabel_22.setText(_translate("MainWindow", "Media espera", None))
        self.nameLabel_46.setText(_translate("MainWindow", "Utilizacao media", None))
        self.nameLabel_18.setText(_translate("MainWindow", "Comp medio fila", None))
        self.nameLabel_30.setText(_translate("MainWindow", "Clientes atendidos", None))
        self.nameLabel_28.setText(_translate("MainWindow", "Tempo simulacao", None))
        self.nameLabel_35.setText(_translate("MainWindow", "Nº repetiçoes", None))

